version: '2'
services:
    secretaria_libro-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/secretaria_libro/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=secretaria_libro
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=dev
        ports:
            - 5432:5432
